language: node_js
node_js:
  - 6.10.3
cache:
  directories:
    - node_modules
script: npm install && npm test
before_install:
  - npm install -g serverless
after_success:
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'
deploy:
  - provider: script
    script: openssl aes-256-cbc -K $encrypted_3d599e52b404_key -iv $encrypted_3d599e52b404_iv -in .secret/public.key.enc -out .secret/public.key -d && openssl aes-256-cbc -K $encrypted_3d599e52b404_key -iv $encrypted_3d599e52b404_iv -in .secret/private.key.enc -out .secret/private.key -d && npm install --production && npm run deploy:dev
    on:
      branch: develop
